### ISSUE TITLE
[Bug] the precipice music disc stops at 5 seconds

### ISSUE THREAD

**Issue by IjAxxDev** [purejosh/purediscstrickytrials#1]
**Describe the bug**
When you try to reproduce the precipice music disc in a jukebox it starts playing but when 5 seconds have passed it stops

**To Reproduce**
1. Place the precipice music disc on a jukebox
2. Wait 5 seconds

**Version information**
Fabric/Forge: Forge 47.2.0
Loader version: MultiMC Version 0.7.0-3863
Mod version: PureDiscsTrickyTrials-v1.0.0-1.20.1-Forge

**Additional context**
As far as i tested this only happens with the precipice music disc.

**Comment by purejosh** [comment]
Wow, no kidding... I straight up missed the length setting for Precipice. I'll get that fixed right now, and upload a fixed version within the hour.

**Comment by purejosh** [comment]
Can we just talk about how much of a banger Precipice is? So good.

**Comment by IjAxxDev** [comment]
i know that's exactly the reason why i downloaded the mod, im doing a server with some friends in 1.20.1 and i needed that disc

**Comment by purejosh** [comment]
Fair enough haha, I'm getting that uploaded right now. The server side is what controls the play time of the disc, did you want me to provide a file here for you to download before curseforge and modrinth approval?

**Comment by IjAxxDev** [comment]
that would be helpfull, thanks

**Comment by purejosh** [comment]
[PureDiscsTrickyTrials-v1.0.1-1.20.1-Forge.jar.zip](https://github.com/user-attachments/files/15777578/PureDiscsTrickyTrials-v1.0.1-1.20.1-Forge.jar.zip)
I've put the newest Forge 1.20.1 in a zip, here you go!

**Comment by IjAxxDev** [comment]
thanks!

**Comment by purejosh** [comment]
Fixed versions uploaded. Thanks again!
